apiVersion: v1
kind: Service
metadata:
  name: jellyfin-local
  namespace: media-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.11
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      protocol: TCP