apiVersion: v1
kind: Service
metadata:
  name: librespeed
  namespace: librespeed
spec:
  selector:
    app: librespeed
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
