---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocis-secrets
  namespace: owncloud
spec:
  encryptedData:
    admin-password: AgA2qXCryl7dkojV1k5dmoZfvsbxJICoCvUj3ls+ayrQZ6zgtCoeDcwCj65ZLTbE6Wm79v7NxoV7Vdn+lLtYWq3Sf4Zt+jQnvqIsXrlqlO0JG8Gthmx4XED0q83PcqanPti3o4DlwVq3s9DGGjAdcxqcHgY8PFcAkyokpxeFSVsKOgE3bgGtb7BXPTooh+P552wzSTBeT2HlcidYHzA6e2ncHJz5Z9ZD/LavVzYb8XXOAUXVKM3CH0jR3WWtm5UE1o/4WHwgALwoItf7/lrpQmzyjyovFWtsHD85LHyViPzx96XwYWU1p6iY1wtgDsuOzEiZxHcZbPzYe4efL8T7LTItjfguP3xC2lTrdxF180zBhY4f8svdLlvcvoAIwSTzKN4Xv0fgyubNvQPax+vW6Ra9RB/00jJf6TWAGcuC91/0sgwMZeuvMyo8sMoncKQiit1xosS2G4oFHjYQ80ccWI2YfqR3meJYVgPrsuS96kZ/aM4hwZmgZ0yPEx8tcT2LNlRbZla/ioK85nCSqMoUezNhHqseemRairj6xHWstpqanwt5NI8UgXMBbLg0NAj/RPQhHVr4efqO+xgyzr+pRZd+bvKoCTQUB14YE5yGsDz8Tj0cpQ6ZqTnXnea+wBY/B1uVRHwA6FzLXPA9kg1K0GUB+XYtOTPTrQvPRU5vHTTOtmgIjqyuDWwYG7OO14NltJcbC1mDwsfKWCwEFXt+G/8L0JmSEw==
  template:
    metadata:
      name: ocis-secrets
      namespace: owncloud
    type: Opaque
