---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocis-secrets
  namespace: owncloud
spec:
  encryptedData:
    admin-password: AgBLFLf3f1INTPGX6g4sB6hPCqea2Oe7nVOTDZnNWAUGKUgquR4D/RvTH8T8fJ9TRQbRYdGpxckSQqcMMQ8j9qFWSs6QdGtMH7ouVeQMBXuQ0ZW6M5bxPQgvTe866FbOffJlwqT3WQbeYFw3Nu674LAkSose1AmsFn/LFUHvpuBFYftWxDSit3yrxoh1K2bIwiwE2r93TwnMOwxsFXNAwSFeq/tZ6WK9Boj61CA1AB0ziwslXzpMQ3JirDeb+AjQa5xKFSlrDzwzQ8+/t29NodMx7m2cgwivaLXznOcgnFA7z+4qXk1qfvS6/hCO14kGph+NeAIk+WeMU/ZDsE72Ahhy2IPSFxZe3USUYXLo24BhWOiTEYVnwJI2d1ewz5NrO3T3sRwXMBot/tTSoZ1zqbOqPfIaiUzEeEcDGj/Sbcnhm0OQMiU6L46nnuETWN/BqNENZjUOLs4fsE5c+ERtrBBb3cGzzk6t5dVS0jghAV3f+EFUDhXBs2E9dZxe/n5t/F331fERi7gVsjtuZeBevb1r1MhvyISLvEsv+8zhuQIaSi4RI4t0CgqHxqzJ+qpZEIOu18RB8ToKES+4izH6XWr+lY5umAfp0ANJxjo/izremYanVeLFtTfAicmnFs3C59lxAbb86zi2kc/D8u+kLDtHkbQLAn0JosfAjBqMC2MCHZO3cGcNQyLh4VGxKRBQTcSH/D5Q+cp60oW9S5qk4a3P493Mqw==
  template:
    metadata:
      name: ocis-secrets
      namespace: owncloud
    type: Opaque
