---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocis-secrets
  namespace: owncloud
spec:
  encryptedData:
    admin-password: AgCoxsHX6ybrKX52HGX1LGScOos89OMoTyIS85kaivKzIiYN7qyTko0obAUWa5XMpGNj349vtyeqyHZxxMPcxmwBmSS2V1XTvs4oGqb0bO02atZ4MUsy/5/EMXEHXrtyyQIZ89i/+gT0kSR1H7+Up29qVCM0+A65Q076AQCT20bKyz4GINh8V3t0lPMKn3D8K4XLo+ZwL5o3V3LBq3VvyOtsoq4HruWco9AN4y7njKdRxUx1aKTtCGEr3p8R6a2SFIh7RrUMkzZVoXdXmMSgk1cLSWK13oU8qtHiH+5iO77lTvbM/xaWE33fK4IJeN1hryNCrYmb3zg8AmSmd4nR3dzIm6xxzAZtIwojjy5JdVoJh9fT3s9zQGg2gyrCSmH5WjuB3mHGfVZ6KQZg1t9bIoT2o+WV1JOSo34eFhc9pB/bVs7g19LZKm2Zz95F8B8m3vzBELt0OtftzWMwppBripo1kcTw4OegN28dVPA+dASam7dR7lkWUZ3G0IXj14KKYXVkvwv9V+5VzSQ3JhFvpfP17F560qyXHLuqiwfnNnULNTjVa52yj+fNVwIPV+M4pVT5dn9tGS/DZPpIib1nOEmqhqgoTd+7u6aKVsFTnXgX40mKi9DdHRaH+XmvNIKXyrraOyCYB4vax87Q9HYz/XBIoxBBVYM/CHv3FC0DXG0BGAzI2LmRCO8GXb55qlR9RYCERV3K5q918um1JHCefXk27lNAgQ==
  template:
    metadata:
      name: ocis-secrets
      namespace: owncloud
    type: Opaque
