---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-s3
  namespace: minio
spec:
  encryptedData:
    access-key: AgB5yNa/oogi7+rxZ5gmqIL7eKgrH9shFWvbeTS4h3+V1S968xRo0LWBAAZBgXcBMRZ3WKPtjuEjlZopSGf6oUtJ8OEKEndu84vZMITjXMo7uM70WbfKU7JPQQcIK/ZdzCEXvgTG3/eSRVkqULcLLzNYoBdB1wXwiVp067eyXaa0wZRWiNQ6+QzebuE5qUdhT5Sj4aQPvERye0s4mWnxXe4HQ94kNHsiApp5vbI5GTS8utGFm2A1YE5lYHb+2jtE5ZWAE2+VlGVu2s5tJEp2hBf8SaRa3X67JmpU+4IONpgVurHItxOzbdSSz0l8dYwMcbv/hW5u2g4GcdcvoZnhFgmFpeoLfJAubzjo/K/mJXDEWpnzzKdFNEFBuXtumY3A8NQQ/P+PbM+jtg5S050vDhydbvvDSOT+Hls90N2Fc9ptZa8NC9I7bOq12Dz1ax+vxvfX61UmdacQvRG2cpZJjTKG7EZxDo1MqLGkxZ+dfraGLML5382S0k4eh5ctzEwPxbvdlcve2j+MHe/GaidMyGX6Jf2aYrYTrEB1zb1qUrWZtGMTlsGSrPCRQF/ujyc0C3pKITah6W7jXiNPCyYOs6CD6wi2ftt2GJiv0NBELhtV/f/yinVWVW54n8HtAHltmkebzwzr/ypksMme/ffqpl7k3bKtx4TAAGKrogsSuy07Ae1Q+/Pa1pjeS8Kpi+7ZnbkqhPY/tMmK
    secret-key: AgBwSk1Ier7BAmGABHOgEozR/FNWvKNcy3xQPlFQwiMA8GhrZgDTlok8GZQHOBWSY/3Vp5fMS5A+tsuhw92QsLhdRCP4QZaJcjQa7hLZvdymq0aWooBQ1Pl6JxcRmRRWMwI3TcCOdpNidcEFWvZvbBTeHqAOxCq/5O26g75URw20U/tOIKCfsvucYmxBe/xJ0byoJAzvcGCCfkc7Qk+BxREYZYpr0irnt6FELiXQIUrKt18SJRfajEov0BJbcKHGkR3LpRccft4sPMGvcjf5kndrsREfZJ/j4I5d8YEN9viuRE8dQVi5ESeAtzrrymsUCJA8D7OjQYuWq7VOwvB2aWeWfw//vTUkMsrqeMImsdezaBfuSbLfocOtUs8vwPgjoyIiGdq7/LNPrT5x60j7vpGQF56ijvdVWa5W/2Cln9ewK2yt1InGzaC3rP1PBh4YRPqqguVveSnittlCgRST6+8eI/7yv88ox3T5j+HMaqFwEckvvjRyTgUKkMz7mllz6+kZEQ+wN+4Af+SLMCWo01+usVbImkKAymTFhkV7T7hKsnbkFnVW9o1rMPvO3PRkuNtFZh6fWm1c0B1g3dA8Lca/jJ+CkH0/qLyFW8gF3F3df0U6kLRWAMAhRb1PddcQZpEtW97+PHBcpB7exLBWDtZkq/3egv2Howl/3qhEHjeV/tfE0BJdty7HyxWLVVhBy8JQYR/HROhK9Yy6Ezf/AF2q6o681FEMSaC8jODe5bs=
  template:
    metadata:
      name: minio-s3
      namespace: minio
    type: Opaque
