apiVersion: v1
kind: Service
metadata:
  name: ocis
  namespace: owncloud
spec:
  selector:
    app: ocis
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  type: ClusterIP
