apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: n5pro
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  instanceManagerCPURequest: 0
  name: n5pro
  tags: []
  disks:
    default-disk-7afea72bb564689f:
      allowScheduling: true
      diskDriver: ""
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/
      storageReserved: 37468457779
      tags: []
    longhorn-hdd:
      allowScheduling: true
      diskDriver: ""
      diskType: filesystem
      evictionRequested: false
      path: /mnt/longhorn-hdd
      storageReserved: 0
      tags:
        - hdd
