---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-secrets
  namespace: gitlab
spec:
  encryptedData:
    root-password: AgC6Kf3T4XRNLL/CC96b6EDiQcyHBcnqJy6v347sF99tDADPmd55y3p04VfUbDpriFh/p1CpNF8taFxpI5S1jEfG9YJbSftKQxd13Zl02RYdPbz7njma8dkTTIspl+6YWMewNonTDegBoklx4rgpRnQOPCN5xFSpP6GiZMLGyKcnjeVyrtSpYApGOqJsonr1Q1I8bLvt1HAYSIQUUh/Kipw9uKYKSTTJXJHp7k/mFR7C6Id/F3iYc3CmumdpotUQzMuSi3ku3ad3+EUF3EY9bdbDCh5o7QkRM9ObTy5YRhEhWugMCSD68T4Z+IQUCIrq3vf2E69ejXZAAQaI9SjzPyoYzVrCRv7hVq/qZnWChB+bSybcnV9jJfOoGQ0Yg5E/cHWvy4lqMFnwylYv6qLOODYliHEQiH+n7FfPsLgLVFGS5fL4FXLvKp+rIYjaoHbc3TO1BOGcLqYEmITlh/vAcqeIf+LQjanosmvp+Ti4RHQ7ZQnIY85V2kP1H+oiyB7bNYGggwUZcVmr/95hjnDMgK/UDiMbhyPDTj0hdRZQ6MCZdn6k4+Mpa1Tv+b4MSLhHj6ck2nFgy1n3fstMx9eygyXt+PSw0RfFnye7NW+GyuvRFzg8EfjgNV1mwsM1sLzPI3dp3upGC1JQLeoPYhMfp5zOrjoTgOqLPdTJ2O1wmgePEddjY6oP9Xm+3aakoNgnvHKTlp0nJit9kPEsaWuppIszVDKlGr4bhbeq3tgsfzIUDdKTGvloVCwIlzCgk4Q3Bo2329kQxNUGZZcyrlw=
  template:
    metadata:
      name: gitlab-secrets
      namespace: gitlab
    type: Opaque
