---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab
spec:
  encryptedData:
    runner-registration-token: AgC9g1J3JM14qwNElQ0eXZbM2GVnCfB3BdH/URiaGz5j4djpkPpP93La0D9+O+DtcIamrwYG5EtRxWN99EiUWJ3oRrwwAriTj1ogZBRxD8JWWauu3pP+SW/ymC6ZCfFoN+DhDFyfYGkeYFT5m70nnVstlfJ5tOO0emai1BDo/RHRI5Cu91/vIDvfu5WW302sDECLPwUllPOiHrmA+viaAim38cG6Rn5hNe6fy2HuNCufNRKljOqlgLM+5lPNwJrH/Q+7mJR/NC0YLHkpr/SEsFwOtCg8T9iAh3TcvhkVSqTpVagktQx42uy7baTpEFaiExWYLuKpgzQkqkV7UDDtVG2Cne6mjpGEgDg8RGMOQu0rbJVcNZ5UrZqoOh1dSeFDuepMsapW9+G2vvV9Bd2MZjCnM/GiQQOenHSr563250Pp4Aq25HpEhQ9bHc4baa+i3jhLFAC6gURpTIqQjxoNKeO4hoARdP3Tt9NU8YZGq5FYKBqclgDfcYR7Az4YyV5iejFfEr4UksBJzahz82DKX9ztD6LThmxZ+MU9amzkVjNIud94M5nye0vjpi1KdoJ6RIyLSZktZNDXxrJtiLknqJ2UKkeY56RR+ZRu22nLQchrfUWOnkzMFJwyo29CbQwHe9791LLY1z86A9HX7nreTw7n8j/ZBaoIzs+XGVSOn9TFRrLdKWvb5wol5vY8/Ikc9go=
    runner-token: AgC2kgmrGrABN5nFy0wlKgDWsQYc+Lxw3aUKw9meHkvwomO/bphqrOwv85EJf6k1DYR2ywsoYIuRP5shb22ls/2lodW6sxJEn/+8uAh+TLIryZ72NazW7sAuUBuTJ2AGw3nJVcladxpKpD1Gs9R3YhZJUIl6pQkp3H2I9kQoas4eaMqJYjKAa3nmP9E04lF2GzkGNZ4XrWyNr42LTzkhpXUla3KyNVJ4XXLNExz0nSNFZeYXMiltWZXhqmgJckS6IufmYmOOIto1o4zGj3dtWVy6YHIcanstCyBf0C8fbQCleK4KCoFBgfASjwINkkOgnpD6Y+t9UdrZ61KU27a0ZGqvpeE9p1Sh+aL4jWT5bklBppvFipuGLWR0BUrZeucPDyKHWge4H25uT/7vklLs9INsgXAm7V2p+gZsmj6for6Nt/w0i0ec9GRPitheEractcLRXaTpiTmE98Cppdv2tS5XS1Vedk8Cv48Isy3Z8EjJuuXzogbZ5bM/Df688T4whk5CDkKpCkLGudUaxCLQvTMcB6do6Qyxgja9sq4+jX4UJJJ3HqIVyAOcT+QtHeni2V96cATMBPJU+vsuVOn4+VzjvClFKjwNaPBK2yyXcD0L9Vf5c6gxFHDZ6zMcEtCMXknnb77MM4nJgdr91Aw9HBe3VfbW7UGWgNL6rAKM4ha3vDt92GJavU0K4rURHaVt2O0Q0wzNkKrHBnRFAcozv7b1yeB3kzcNkpKRCV0oc/+U2R8pipIxkvMsacwEtlW6M0GOyahjxqbvHA==
  template:
    metadata:
      name: gitlab-runner-secret
      namespace: gitlab
    type: Opaque
