---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-secrets
  namespace: gitlab
spec:
  encryptedData:
    root-password: AgDE5/1f85kbAgLPRDBWNInrA0EnOoJF9ZYrQkGicUmHOhbwbv/s9oV+0EQRl8E5wI7jqQ4SsXeaiPAMe4/rSqRRTjaEFxg4EmveBw2I0EKhtIh+cNyyz9lvdgKPfjHZgyDvzhzMn0BRgkKvVAdT5AkjqBtVkCG22EaesO4VqgJYvPLkzCiCUZTE7fxJnxfjngPWeuCXbXeXzRIJwhsZaE5U6TMjIvyLpxhlMlplxSAhEM5HMUffIeMbPVffh7oWKjeUaVL2sYysNvhEcvpxJI6UDQgqLpFhLZzoESQ0PJJyVULcBtfWzezFx/0SuZPHihUIJ7S0TfjlY4giQ7RjIisTMlpGNRiVq8nXRfOc57g0q8gXYUpKw0oPelsgpx4bL45qmINjg2Lpe++SHD5h7brvciGG20+UGqPbTLO5ijOZMHV1OxXDzZ4tzeZHxL1XYI4gsPPjqMhQ/hJAdBKv5Npt23UQlIcLImA/EOro3WuoaBHc1UYLOw8LkbCqqKaJwm5iGSBQia+FpOb8L2A2HVm+SebbSc4CLr9XN+0OyDb2KPanLYca/qGZC32VJyTLZL8lhJM8UltwSsY2LsnRnErV0szPI1O8PVNz16qamrnuPpHKjshuj3/Ja/Ll3fh9vcFoZaXI+SPrHBWzVWlfPPbPW3eNGZ+GMX+k6+7EbErOZ4o7pRw+JnnLfxMduh5XlpX/suthkt+JKuaGmImnbi9XdZYWTvgN52j4pIaoS8yqCFLhjTGqhoj94QRrA8WIiYrFVp1R/fn2waKsd6E=
  template:
    metadata:
      name: gitlab-secrets
      namespace: gitlab
    type: Opaque
