---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab
spec:
  encryptedData:
    runner-token: AgBGm7dP3UVKSi3YENN9AHxZdInBjv/V4qxG8uVe2oND1aw/EvEU+T27hwUvBoqUVJ+a7szuYZ2n9kK07Z1+tNljJqdZnjHRSClH6+x5AQf0jq7lfJ/bIFVG62lXQcJXBIoivOFASIB6U2G+HLKR+PL7aXDBajRfH58z1QcaUKhCckEGVWKdRQT9eQZiCit54k0KxJ7fOJoIUZAzR/ONnyKwMWxvWepOgr7nUpMutmaBmmkD0jrTa2PGdPJx3TKR7SAC4wosaBaYiMaj8Nfumzx8+7iD4SGCkcaQRr80extqK4zj9ViFpKfL38DUTwEdjxbZymp2dunhGvfjuBQOuFAqZDIu0RuGbgz/Bsli+byh4uvdZacZ8TAM0ub6NBJSq2DKgIr5FqrpTfm6CI2F9jg98wIIUXpT3UUww34Kuep7KATrh05N+gFyNh+qWHR6LS0M3/47XRTIH0Vmx7/+W4aswrLi6KhrLxVW+SLi07fKsQYaHiu3Bq9Fwo7oADA5I/go6s6SdVrZf/X+l+ZcE4ZoR1N32hr9KNyvVX6nUOwVQssSt30NpkCTJKojXx9YjgzVOY1dtg1WQFJnHW+BZBZ1Kp0Hh/+/yzjfybc6y4jj8EYz4MVohLtwTPaZw1GfZqV/MPkAGmo2+znKLJa3yQJSQbl0zn3JjKORiShp/WwB5uhMyELEjyS1fN0DiWTrC8bKjhC8hCV9AiMSaAXNFDudPB+wOMwlCzDK0QqerrR7t5lSPv98ejUOsS+xY9ACzP7z4RtGNmYKHA==
  template:
    metadata:
      name: gitlab-runner-secret
      namespace: gitlab
    type: Opaque
