---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-secrets
  namespace: gitlab
spec:
  encryptedData:
    root-password: AgALWGDQyqsDUpjPeo/2ReoqjB0KdoQXVoHByXkmy5/j38xy5jFca2CnvemGMv56PPFxsrLuMYkt1AYPg8Cl1hTKAhWNflGNrF8jXUQ9NIMlbX5AkmbBEk1PkNxXuZVeD8pJbIexKlbYfmGpKFijul5n5uxBGzyrwvaadzXrEpj6REBAo1xdWNCyr7qi1WYoRNthqP6XoAp37Jb5yGCbahvb4OwxA2gqARxz/omth324HdU9t9VcHxBWnMFgzdYDcx0Bhdj/vYlCAduMnMput5RglYyIWNFbLybpZts1NEff23lIhENNNpUrWPjFigld4NdkbItk8fBgs099JbSbRHUSf5BZcRBEKQ5Gba4TiQ15TDfKoxnI9NHFVZpiErVAWEbXop/smydWhFmdSHiVPENHGpqBQ5+rQpwGG0hkZ6/S9+dYTxj2OS4vDXWuIqiOKL3Qww33FAkxIj/uNst8JUasZ8mhf/fPyF3F8lcTiH7rVKR6uyTsc+QPbvW97tGnCcODhDc+2XEDf019hqEuy7h7PmBjfrsdfZFAA/m2uHwEawvNZb1/eidYEV9rxhNe51HbKVdzxd9es8Ohat2RpGbQdUXDSGcgwAYxXVbeBuAKURRr3pEuz6JOnP3cZfX/sWSlaUcrChK1T/1kv0nMlNZ9+aSUq6Dq4KURqOnDjWWfHPkPmQaOJrnFD6OlPKXvbE/Q2Tp6Q4MRqsYUHe1DslHkzkESXID/KPV1ojqKcfuttA==
  template:
    metadata:
      name: gitlab-secrets
      namespace: gitlab
    type: Opaque
