---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirling-pdf-auth
  namespace: stirling-pdf
spec:
  encryptedData:
    password: AgCGKkx61p/lELf6BCEGR6yZOimRkpJcZp28Sp4u+9gFVDYYaGm/H1leGNQowDWb8KAED0vfF0C9McBdsru1tq4cqX1BauoPGuNgXq6sXXgTObBOe7GJiC5dncnrYLzpu1aboq9OGPyqsWIKD1TOAhuJGeWlqAAYylOyLF2IDXQCnG0xoKP5qwsRzIY7/7vmtT9nScbhBw6V9ky6MLwdrhsIJTXw801pVZnry3eOeTKWTV8gKt2lPh3xOpfgVcGBARtibFfApqNIRqrvbFv7NAS46bdo+ogNBewvVv1gSq+bljiZvWMNos18Y5Mwvr8G2bvIbBq909yS07+8jGyTuMVp7a/AyYy7Do7wHdySHkKMX41jYKgXAkKzmwr9RyiUbhmVJ697YhWg+vFe3xnzkCUr2hWESepnL5yCDZ1fTUGDQ5ogTTtGs8cWAcCheZ2mOohzDY9R844Eizx4BKv7X4iKZOQu15cqyhNBpeDeeet6LWGWZ/oOCu2s1RI2PZVFz4MJlq7Kur6MaJCfQ0wubyB6JNvT6o9km8h2Bb1+6F9nKFNLXEFx+xapPBvN0y85uJtrDqkl5/HRS0WtAHlk+p2+hARxRitPFBh0eBa+Qh7GLzqbWPXlF//TIpJJtMe3Y1VhXIp/LV3GE1dnoQbMGegMSwlJOumyRAmR0Uy3g25k3DYXb5Q0zFcDEGP+aaKSM28jjT/JqjMTURjFvRhdkfSiPLPUqQ==
  template:
    metadata:
      name: stirling-pdf-auth
      namespace: stirling-pdf
    type: Opaque
