---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirling-pdf-auth
  namespace: stirling-pdf
spec:
  encryptedData:
    password: AgC41Uw/Z90iMHh2c5tryL1mXUGZX0P8ow1Sq8UDaWlPjBqfdNdR2cMIbh0IaK9aE6usm5nZIdcLoZ7+hbJAokmberfqKtto6uIE2lHGvp5L09T7JkzuKn8hVeiHGZhP9lxe1kDifTg63NS4CZwnv5TAzGkrDayc4PkPZtYWD16UwU6I8Cx0KwNkSDPfzvePD9DY4iTIMjbAkDWZw5nRQgkU4EkGxBhm87+8w6gtfAfjrLuQjpT1FqAZro63cQFztUu8CSlXV1Pbn9om7z8WkzRLLFAwAASWarQCQ+F+7vfD/yCJU6VNvwe5CCLIlzG65DP8bLt5DYQKGDDx+V5bowBiW6TpsvsoGplEGIovt5LXA/AQv5FoTF1fIBBmc9QMZEwLEe8vooXoG1K6wSElultmszVz+Q67ViB1jcrcGtXw8yaLztKQeR3BsPzLmZbyxr6ZMjyFUak0pm52FU32yulBdxxXYx6/uL9LdAzt6jVkWT+91JjTthAK63U4e48oRCnb1NAEc7Cz+SzYZu1FRziFjXxguW0DGeLSQcW80h2bQPap1Oj9WBNcVSnbdw29VOIAi9tfys3PXKI/VKhLpYshNY9xiMuy68r4k8OvxO72TEfNqDydugC8i06hFtffB0Uaw835Gm5E6NcKDf1uTcYnkpWoaBG9ngx4OPG+r83BrS9/vz1X85XL4LnCsYI/d0oBVq3+duCY0mrZSimRHJimSxof2w==
  template:
    metadata:
      name: stirling-pdf-auth
      namespace: stirling-pdf
    type: Opaque
