---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirling-pdf-auth
  namespace: stirling-pdf
spec:
  encryptedData:
    password: AgBgEupCWpcyB0HpBbTs7czwA30uph2nfCcKNX/FuUCnf87zfuYKHj98NzWjOavU3Mxk8TDeU82aFwTfdvXNpvhZ3L4zc+43Gs5IdmJxrTl1WlR5/sWmVTEm5GNvbZ2xsr1xWwwfNA92SdA/vEAPljMITbsdo2wRPX2bcSEaUdB1s9ic+idrfR7i4BHuuVs2iiiCMWhVjeFQ3ZmFEUTvW2eDkazfE4yX+ieOd4ONCh6fH1DEoX0Ku9N+k6TfEck9qE/rCpx+evwVEuzar9MvIc/j5dUNCOQNoakB+uPhr1M7fJ57KTWYpExfg5kPuHeNnMQIx+H9/voMn+PLdDICnR9v89yHxKWBnxU4YA63VaXNhd0xA8DZDsXKtyMLTV3qqZ0TgAo2d3HFs1GUnfvEQGPTO/DwUwWWI6fY9ZUMLMsDgeA3WyFTCrmJr4I5Kt1OmAanEq1sXNSxlWFJVDe+FyYPFBKF5Mmzyoscbt3w5Sl2D9imHvp+CYkKCP1Rplp57sYcmIVd6N1Bg9RERPvb6o2ELhLDZxNV8VUYKdbE+An7vUsTVMjAP0YZ9zuIqxJXkliGvaqpWf3yBlDpRo5b3E/eZd/n859upctAm/xfRhWIPOgjzW+YjLx4kdUE46rDIXu+o2y1+YjcPMSGyfQ25VanIzdVTzb3+Aza2d09RyqB5B9sLoJQBqBQHRGXbM2MaIkOBkBdqTdPgnmNbTrTydp8C4czeg==
  template:
    metadata:
      name: stirling-pdf-auth
      namespace: stirling-pdf
    type: Opaque
