---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirling-pdf-basicauth
  namespace: stirling-pdf
spec:
  encryptedData:
    users: AgAJFgbcH2glxRDl6H8J40nd4kQ08mcrXjJV57awGxWys4DP9PErMIo2jHEBfj+pCos1Wc+8xtdArZNWAJoC/XuuqyCGCXvPITWhtAtxjfcnSiu3hVN7ZYxzAN2DhiV4L9b0I9JQsIb9qe5dwGgKaJUl8zUCGR5L2JIeY69f7ebUW4yPzwzKrLOb+x+AHeamANwkR/e6TnnAxmuGhWReoLLvbToUB+Oyhb18RPL9GrY1VDekJ/kSqgBIFhT2rKmAduuFXfHwQX7LSwVap26mDwHFQEZHLE/dookCqlkN0IhR0sVpyHu06/9EwDhnCU4B8NVotqGx0CIHLP9dTSWMNDbsq+bas5+8xUgTSg/SB7lHqHtxFy4xTFxD5iFFUvy+agdLou/ksE300F1HjVZcmaN/gfFVDUs9E2rZjpU3OEbUYh9wMi1+ViexS7i+25Ys5KlKWeml7XQ5TlaSHE/GgGu0cQPKLDuSgvUtNPJgWQHpIGRzvcnActzKVkCn38QcxyQESHYfnTe/VTsmFn3ULhUA+NWSxO6bkCj+g7giAi0FrNN0zjwY4UhWENs0EJdohuvDnv1JQFRjJCoci0v/L80dvk0DECg6sAQV1UwTuLTtD/bI3be6zqCcegL6g61Nvrapyg03Bt5SeurPx79PFM2fg5Lk2aP7TEDI/1MW8nRM+CF4hEJ9H82sY0Ic1s5esDYiORS02IB/Aogm5W03HBskzFIax85WRwUNWUMKPyxxR5VsklHMReOfV2dDQ1cdKfJX2UEZPlmDFxfF2Oul3RZ5XfJoRc/B
  template:
    metadata:
      name: stirling-pdf-basicauth
      namespace: stirling-pdf
    type: Opaque
