apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console-ingress
  namespace: meeting-bot
  labels:
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`minio.local.{{ .Values.cloudflare_zone }}`)
      kind: Rule
      services:
        - name: minio
          port: 9001
  tls:
    domains:
    - main: local.{{ .Values.cloudflare_zone }}
      sans:
      - minio.local.{{ .Values.cloudflare_zone }}
    secretName: local-{{ .Values.cloudflare_zone_hyphen }}-tls
