---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: values-secret
  namespace: traefik
spec:
  encryptedData:
    values.yaml: AgAGy2vVAI1n3ekKcRxhGSrYhIuVPf9JGrUJggn97epPR0jdbYt+2T4nNvAIy8FjXHMy//qLNEaOCYEONopMu8FaKp0dou8Qp9g8C5AR4ObB8sI14MYRVAHkhvkoGKT5wlAkmMEqHa5267j87bV0MUFNfD3YF3XvGJeSD7yjx2RwN4IPsq/uV6YjqTYavgoR3jvRK/WweRt49dLl/zxIq0O+CDlQsM4yWr3vXar0pzNvfMMTuRQVZjnj5ufvJuPpjFnjd4jm32a0TUosSS8OsAqQoH0gR5VC1/sSAfLLoWrvCcDgcpCgHxov76k6GOqhbpR7Lsx1RW+Pjbsv3xh2+8RS253g4XHHL9gVx3OndiDHWp5f7MWI9aHsN6l9JXUstd9OJIKzK5r/g6nRJNjAPwJh19JxA38O4f39Z1YqohTHLPlSY1SaCTGHDjXgif+VsFaX0YbYVo9v+zv+gYVS/EVKZguKWE9bdT3HOWa3oFC8DJmv/VRzypol7fA+lD90neWcuuw3JgeUJYkkyYJP2//cdGG+09U1R9A16pwWvr7K/X8YI7SdROCLd9Qrjq6eG7c0EegioWcptvPqteINSvnBQXJ64P3XCp7caRWs44OsMdL5j7kmTDoL8TrclG05X3lsKTkv7wFJLNeRzOGp5WHVNr4snnZtgvZjOvtTlK4nsP77v4lifAGJq7QvrYpTYDtat9t7fi63Nvbegsju3Gh+EknNzoajQQiXpvqfirRCTgtkc/17wKoikm/Eq8TZ4zFvqg==
  template:
    metadata:
      name: values-secret
      namespace: traefik
