---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meeting-bot-s3
  namespace: meeting-bot
spec:
  encryptedData:
    access-key: AgB8W87NrrLufUvy3mKJ8rg2X0UesN5mseQejanLjUGk1uMXK/UlVDttoyOHCpr0WHExMxKYISiBz79WImWShgjx+uZbyLuUABO8GpXLen4X7tT6eZ18Eo5iTnX+HTtmigfkWwYcWSxLU0OVcipXGT0qKbfL7is3evko2C0yrlhC1WjZTEnhoKoTbks+X+w+0Dt5HER1p1NaC/RM9MUa5rIq3uGDIisuikgXlXcKfr0w8i1Z4JCW8wVohKq9jAvrhNyXYpSs3OYXxdcw0f0Eh3l/hA6F5Yyb6Fo3ZOpP2ySHH20HW1UCeA49pPr91JeKY7vCsVC1UcswYYsAe7zQ5FQK1KB5DCCDhsSPkEPRpTNCmv/W2WZofNgFI4EbyT2CEpJoH1hDV5b4ete88KWYKjjq64YiazLrVAJWEAsJUODSh21DBVzOtZxKTsUa28yTP6UTAXlGXPbeVHIhqXAFpU4ty3wFZZojFMhL+oHN9KwRhIFSfTFNstA5LxfnB60czEQ9XYzWUt6uXX8KbD0cMGsKn9lsGEtMGmCEQqN/6RyvM5kDz7ld0f6sqhMkV5vjqs70BaiBLIkPL4QZeQFP4hW5qa9Lohq3ELgWuwN57MvwtGn+TL3upsHyrVJTMk0Sygn/A3jhG5NZUHCIxwbcSJjJtWAKwNyQ+Cl0Wi9aQ1s3Z1wTTlBnXWhCdXs5fQdSQ6TkMvc29eBg
    secret-key: AgAsNiu+HvHkvkJwWW/QbFuccgzRwFrWbFxY+bvLVtw9ixwvzTZQfIcYGYlJHcry2Mf15Hw1kuxh2IiscTEu0xRUo5HXr9uMoB8ktEGHj6V4eGC/pETrvfGUfxLksYyZftE68iKg28GVJ9unRHdUb6D7hUSs6/nEwhOsSyGZ8YK+oyiEPpUVvLNKmIGmb5x14pORXBmj7tR69jGZt6JRTH/nTiTibLZyyOh1WniTAFtEYeGlgXctoq1sfSTnv8B5neVJrjTiKgQk/8bJebYl+u6U3S6jxifF62b155p3qar9QJujSsaeLXQdDneDTp04ldlzw2FVgm6svL09QEN8lcXfuLfg6sZZOBW+Mvs2Dc6MWssKSO1SiYh/qpL+FtvSKgeoDGFfIFL1dtiFHe5iQazyrHweoTlvqrtrqG2NpdSaXRp0MMhkg4paCUnW/RIZCCjpxvw6GDpcsPFpkPkReu+1t7lnTPeCOgzJ6lHGydS3FtK6bg+jqSe+Egj3O+Q8Wv8KAOiUE4QltQHFB6QCcp/eIrWQqgFUGZWlPVb8E9BpgKrP/1uJPJ8TCbteMwNBQA6T7HQuLXWCc21BXH2CpqNWAEdQeWCbs98DMzfvp729w93hIh0xuqjB0t32wSR7g6QPh2pyD67u/vgRyWlSe8C/Tob7QFoRRMQpvGSqaTtMCACdDg9jUPeHQAgt7KIAZmV5wj8OEW6gwClRcfo9Kv/RdVkMQaumjPenh7bT6oY=
  template:
    metadata:
      name: meeting-bot-s3
      namespace: meeting-bot
    type: Opaque
