---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: values-secret
  namespace: tailscale
spec:
  encryptedData:
    values.yaml: AgBhNKVNQRuTgNBGA7OGarCNyFaM0eGtx/unjf/KVq/fHF0b2E7slurNsjhNjV9fLquAVNMM4Y0DK+wjO2CE67wZaI/K5+ZosiyJNJcJmsxGlnyZbpUNr2LPEjT4OpyLccn5BhAPnvIWyTzTSNb5bBX8vmoLuUJXZJRZqJdOF0NmvbEdK6+N65WOonvKXms+GOCZHTWVth16aptpxzqyxODH956iIfLwpzHk03XhNvssYyFTDFmVW36gAK+5T70a7HgAnmQCRebHCLOq69aifSvJmzeh0L1H5pd4kfDTMVjNXuT24S4+eK1Q9l0LSO9W3UlxWuaEOD5PQyBMPFQNZXS0OeW6x2gJXCDfuM4mD0c/+UVuyAEB2Gp9VFjBbryO0/ytAkMu1iSshVJJ+Y4EozuxTYHjtaZl9K+zt5LJa64IPP6LCVCRJyqZO9YnK3p7FVnF6GuiNjSR1NdeyfUEZ1Q1J6E74MYPt0dDTvfHngaASTqdnHdQCbYVQu4G9fnfrFskbZb8/+jxMoCG/cGAYtF8lg/rhcUpOqejscX1pR2q024f3K3xiMkjPaeEB0KE2Yt6x8pFfLB5YpZGcudPOfTz18aqAGUGxmzKRqpC8t41E29DPOJXYphYn9oTE38ndUiPVFn/tYdN9q4dns0359RQaA0NPM9TtrEjdGmLxqYCgZlQ8yy2dmqr4PzkLc8JEn06CXF3jrkyAXn/6l4qeJZBr2SvNdxlChoonxYvqPUO2dayIO0gbjV3Ar2hJwsU5I6wAP8byx3D5O+ub7GKHXzpDzffKPj/u/d7qeK9F22UdJKgIVZtP0lQeAk7+SucQCpqrsdRkizHj77MrB7ffDfnncSzjrD90U+pSg==
  template:
    metadata:
      name: values-secret
      namespace: tailscale
