---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: values-secret
  namespace: tailscale
spec:
  encryptedData:
    values.yaml: AgADQi4J06hlQlXuDgpHckmkSvhG+5RpmjmL3hbt4VVwOliNkVNXwgmeErMYySHioHway42kIWrRk/cubfmrqcMjTKR203lxWBLpPcdg8utYeUaI+xVB3u9dFqW4np98T1zPV+cOR0xP42LGIzyd1jxeLv4iRmNvRLGa+R9qHLneJ3anBe62J35TQuOZJjSjZeuPlzaptzJwERdYcsYpfLo2w4S/RjWmZ2pJZnG6GjgWkKVTkqzUybhjEJ5l1MKFeoOTYBtg0Tq8jFfUXlJyYHxBWJpGwgmpyDcy1ZR8hhIEaD99Kwlb/3nrqzS5WNsH7HMyXFU0F/x6AkHS+KjMEI81zNgBguYfmkBPIg9UjWobV/pO5CKD6Iu2v0Bk7U1DRKfEiWe4R0oEI27cJzag2M5QCULDZdshHfqH0fhPkzNCifj8zCh9Kqa43uhq8Mz8CNF9RoHgWyPCZDfbLqJgXzPwbKtmCdkd3yhyT1zBcoZJ8MvZ4gh81SuELnd2jhruDtw6DXwtgo5kQuLwbKpPWLr4RLkAWZAHyxCmcu63uYRVlicfovkQ5O7np6oeIgcICACssWvbViD28nLcTCvn5CFoUnBw0GmDrGWarnN8/p7pG6UXC/g8Sfi1ia0tYNmnIlnd0OQDShq4UGhIsAhWLjwlzR1FkC1ZbOKhms7bJeMdgJLIq7ll11ec1IiBdPhwQl2HgxApVO5e6dXsiyntptMJVFXWdYvSNDmbOTGUo/+AL7ts4cqcr5LEEQrkfwb/LX2KJ5trJ+WxgUxNIy/uzX3DbXyP9IzENi9eu/pFtLPI7/4m6RDs5WpWiG6EyBYWAgo5VjQ9EKewWxSyx8ymZNdST+a0Gg0DdvstZw==
  template:
    metadata:
      name: values-secret
      namespace: tailscale
